/camera/camera:
  ros__parameters:

    enable_color: true
    enable_depth: true
    enable_gyro: true
    enable_accel: true

    pointcloud.enable: true
    pointcloud.stream_filter: 2

    decimation_filter.enable: true
    decimation_filter.filter_magnitude: 4

    rgb_camera.profile: "640x480x30"
    depth_module.profile: "640x480x30"

    align_depth.enable: true

    spatial_filter.enable: true
    spatial_filter.filter_magnitude: 2

    temporal_filter.enable: true
    temporal_filter.filter_smooth_alpha: 0.4
    temporal_filter.filter_smooth_delta: 20